import { BeadColor } from './types';

// Precise MARD 221 Color Palette based on provided charts
// Series A (Yellows/Oranges), B (Greens), C (Blues), D (Purples),
// E (Pinks), F (Reds), G (Earth/Skin), H (Greyscale/Basics), M (Special/Vintage)

export const BEAD_PALETTE: BeadColor[] = [
  // --- A Series (Yellows/Oranges) ---
  { id: 'A1', name: 'A1 Cream', hex: '#FAF5CF', brand: 'MARD' },
  { id: 'A2', name: 'A2 Light Yellow', hex: '#FCFED6', brand: 'MARD' },
  { id: 'A3', name: 'A3 Pale Yellow', hex: '#FCFF94', brand: 'MARD' },
  { id: 'A4', name: 'A4 Lemon', hex: '#F7EE5B', brand: 'MARD' },
  { id: 'A5', name: 'A5 Yellow', hex: '#EDDA36', brand: 'MARD' },
  { id: 'A6', name: 'A6 Orange', hex: '#FDA951', brand: 'MARD' },
  { id: 'A7', name: 'A7 Soft Orange', hex: '#FA8C51', brand: 'MARD' },
  { id: 'A8', name: 'A8 Golden Yellow', hex: '#FDD94D', brand: 'MARD' },
  { id: 'A9', name: 'A9 Apricot', hex: '#FA9C5E', brand: 'MARD' },
  { id: 'A10', name: 'A10 Tangerine', hex: '#F67D34', brand: 'MARD' },
  { id: 'A11', name: 'A11 Peach', hex: '#FEDB9B', brand: 'MARD' },
  { id: 'A12', name: 'A12 Coral', hex: '#FDA275', brand: 'MARD' },
  { id: 'A13', name: 'A13 Maize', hex: '#FDC767', brand: 'MARD' },
  { id: 'A14', name: 'A14 Red Orange', hex: '#EA5944', brand: 'MARD' },
  { id: 'A15', name: 'A15 Bright Yellow', hex: '#FBF55F', brand: 'MARD' },
  { id: 'A16', name: 'A16 Pastel Yellow', hex: '#FDFE98', brand: 'MARD' },
  { id: 'A17', name: 'A17 Sun', hex: '#FCE271', brand: 'MARD' },
  { id: 'A18', name: 'A18 Cantaloupe', hex: '#FCC080', brand: 'MARD' },
  { id: 'A19', name: 'A19 Salmon', hex: '#FD7E77', brand: 'MARD' },
  { id: 'A20', name: 'A20 Mustard', hex: '#F9D670', brand: 'MARD' },
  { id: 'A21', name: 'A21 Straw', hex: '#FAE393', brand: 'MARD' },
  { id: 'A22', name: 'A22 Neon Yellow', hex: '#EEF979', brand: 'MARD' },
  { id: 'A23', name: 'A23 Beige', hex: '#E3C8BD', brand: 'MARD' },
  { id: 'A24', name: 'A24 Light Lime', hex: '#F3F5AA', brand: 'MARD' },
  { id: 'A25', name: 'A25 Honey', hex: '#FDD784', brand: 'MARD' },
  { id: 'A26', name: 'A26 Amber', hex: '#FEC832', brand: 'MARD' },

  // --- B Series (Greens) ---
  { id: 'B1', name: 'B1 Lime', hex: '#DDF138', brand: 'MARD' },
  { id: 'B2', name: 'B2 Neon Green', hex: '#65F345', brand: 'MARD' },
  { id: 'B3', name: 'B3 Light Green', hex: '#A0F786', brand: 'MARD' },
  { id: 'B4', name: 'B4 Bright Green', hex: '#60DE35', brand: 'MARD' },
  { id: 'B5', name: 'B5 Green', hex: '#38E058', brand: 'MARD' },
  { id: 'B6', name: 'B6 Sea Green', hex: '#64E0A4', brand: 'MARD' },
  { id: 'B7', name: 'B7 Jade', hex: '#3EAF7B', brand: 'MARD' },
  { id: 'B8', name: 'B8 Forest', hex: '#1D9C55', brand: 'MARD' },
  { id: 'B9', name: 'B9 Dark Green', hex: '#2A5136', brand: 'MARD' },
  { id: 'B10', name: 'B10 Pale Green', hex: '#9BD0BC', brand: 'MARD' },
  { id: 'B11', name: 'B11 Olive', hex: '#627033', brand: 'MARD' },
  { id: 'B12', name: 'B12 Hunter', hex: '#1A6E3D', brand: 'MARD' },
  { id: 'B13', name: 'B13 Chartreuse', hex: '#C9E880', brand: 'MARD' },
  { id: 'B14', name: 'B14 Spring', hex: '#ACE74D', brand: 'MARD' },
  { id: 'B15', name: 'B15 Deep Green', hex: '#305335', brand: 'MARD' },
  { id: 'B16', name: 'B16 Mint', hex: '#C0ED9C', brand: 'MARD' },
  { id: 'B17', name: 'B17 Moss', hex: '#9EB23F', brand: 'MARD' },
  { id: 'B18', name: 'B18 Yellow Green', hex: '#E7EF4E', brand: 'MARD' },
  { id: 'B19', name: 'B19 Teal', hex: '#26B790', brand: 'MARD' },
  { id: 'B20', name: 'B20 Ice Green', hex: '#CAEDCF', brand: 'MARD' },
  { id: 'B21', name: 'B21 Dark Teal', hex: '#18626B', brand: 'MARD' },
  { id: 'B22', name: 'B22 Midnight Green', hex: '#0A4241', brand: 'MARD' },
  { id: 'B23', name: 'B23 Army', hex: '#353C1A', brand: 'MARD' },
  { id: 'B24', name: 'B24 Pastel Green', hex: '#E8FAA8', brand: 'MARD' },
  { id: 'B25', name: 'B25 Sage', hex: '#4E846D', brand: 'MARD' },
  { id: 'B26', name: 'B26 Bronze Green', hex: '#907C35', brand: 'MARD' },
  { id: 'B27', name: 'B27 Celadon', hex: '#D0E0AF', brand: 'MARD' },
  { id: 'B28', name: 'B28 Aqua Mint', hex: '#9FE4B8', brand: 'MARD' },
  { id: 'B29', name: 'B29 Leaf', hex: '#C6DF5F', brand: 'MARD' },
  { id: 'B30', name: 'B30 Pale Lime', hex: '#E3FBB1', brand: 'MARD' },
  { id: 'B31', name: 'B31 Grass', hex: '#B1E596', brand: 'MARD' },
  { id: 'B32', name: 'B32 Fern', hex: '#92AD60', brand: 'MARD' },

  // --- C Series (Blues) ---
  { id: 'C1', name: 'C1 White Blue', hex: '#F0FEE5', brand: 'MARD' },
  { id: 'C2', name: 'C2 Ice Blue', hex: '#ACF6FB', brand: 'MARD' },
  { id: 'C3', name: 'C3 Pale Blue', hex: '#9FE1FB', brand: 'MARD' },
  { id: 'C4', name: 'C4 Light Blue', hex: '#44CDFB', brand: 'MARD' },
  { id: 'C5', name: 'C5 Azure', hex: '#03ACE3', brand: 'MARD' },
  { id: 'C6', name: 'C6 Sky Blue', hex: '#56A7E9', brand: 'MARD' },
  { id: 'C7', name: 'C7 Medium Blue', hex: '#3A77CA', brand: 'MARD' },
  { id: 'C8', name: 'C8 Blue', hex: '#1052C0', brand: 'MARD' },
  { id: 'C9', name: 'C9 Royal Blue', hex: '#3349C3', brand: 'MARD' },
  { id: 'C10', name: 'C10 Soft Blue', hex: '#3DBBE3', brand: 'MARD' },
  { id: 'C11', name: 'C11 Cyan', hex: '#27DFD2', brand: 'MARD' },
  { id: 'C12', name: 'C12 Navy', hex: '#1F334E', brand: 'MARD' },
  { id: 'C13', name: 'C13 Powder Blue', hex: '#CDE7FE', brand: 'MARD' },
  { id: 'C14', name: 'C14 Frost', hex: '#D6FDFC', brand: 'MARD' },
  { id: 'C15', name: 'C15 Turquoise', hex: '#21C5C4', brand: 'MARD' },
  { id: 'C16', name: 'C16 Denim', hex: '#1858A0', brand: 'MARD' },
  { id: 'C17', name: 'C17 Neon Blue', hex: '#02CFF6', brand: 'MARD' },
  { id: 'C18', name: 'C18 Dark Navy', hex: '#213244', brand: 'MARD' },
  { id: 'C19', name: 'C19 Steel Blue', hex: '#18869D', brand: 'MARD' },
  { id: 'C20', name: 'C20 Cobalt', hex: '#1871AB', brand: 'MARD' },
  { id: 'C21', name: 'C21 Periwinkle', hex: '#BFDEFD', brand: 'MARD' },
  { id: 'C22', name: 'C22 Grey Blue', hex: '#6BB1BB', brand: 'MARD' },
  { id: 'C23', name: 'C23 Baby Blue', hex: '#C8E2F9', brand: 'MARD' },
  { id: 'C24', name: 'C24 Cornflower', hex: '#7EC6F8', brand: 'MARD' },
  { id: 'C25', name: 'C25 Aqua', hex: '#A9E8E0', brand: 'MARD' },
  { id: 'C26', name: 'C26 Ocean', hex: '#41AED2', brand: 'MARD' },
  { id: 'C27', name: 'C27 Lavender Blue', hex: '#D0DEF9', brand: 'MARD' },
  { id: 'C28', name: 'C28 Slate', hex: '#BDCEE8', brand: 'MARD' },
  { id: 'C29', name: 'C29 Indigo', hex: '#364B88', brand: 'MARD' },

  // --- D Series (Purples) ---
  { id: 'D1', name: 'D1 Pale Purple', hex: '#ACB7EF', brand: 'MARD' },
  { id: 'D2', name: 'D2 Lavender', hex: '#868DD3', brand: 'MARD' },
  { id: 'D3', name: 'D3 Violet Blue', hex: '#3653AF', brand: 'MARD' },
  { id: 'D4', name: 'D4 Deep Blue', hex: '#162C7E', brand: 'MARD' },
  { id: 'D5', name: 'D5 Orchid', hex: '#B24DC8', brand: 'MARD' },
  { id: 'D6', name: 'D6 Light Purple', hex: '#B37BDE', brand: 'MARD' },
  { id: 'D7', name: 'D7 Purple', hex: '#8659AA', brand: 'MARD' },
  { id: 'D8', name: 'D8 White Lilac', hex: '#E2D3FE', brand: 'MARD' },
  { id: 'D9', name: 'D9 Lilac', hex: '#D6BAF5', brand: 'MARD' },
  { id: 'D10', name: 'D10 Dark Purple', hex: '#2F1C49', brand: 'MARD' },
  { id: 'D11', name: 'D11 Soft Purple', hex: '#BEB9E2', brand: 'MARD' },
  { id: 'D12', name: 'D12 Mauve', hex: '#DC99CC', brand: 'MARD' },
  { id: 'D13', name: 'D13 Magenta', hex: '#B50291', brand: 'MARD' },
  { id: 'D14', name: 'D14 Grape', hex: '#8B2795', brand: 'MARD' },
  { id: 'D15', name: 'D15 Royal Purple', hex: '#311E8F', brand: 'MARD' },
  { id: 'D16', name: 'D16 Cloud', hex: '#E1E5F1', brand: 'MARD' },
  { id: 'D17', name: 'D17 Mist', hex: '#CAD3FA', brand: 'MARD' },
  { id: 'D18', name: 'D18 Plum', hex: '#9A64B7', brand: 'MARD' },
  { id: 'D19', name: 'D19 Thistle', hex: '#DAC4DB', brand: 'MARD' },
  { id: 'D20', name: 'D20 Violet', hex: '#9A35AE', brand: 'MARD' },
  { id: 'D21', name: 'D21 Deep Violet', hex: '#960494', brand: 'MARD' },
  { id: 'D22', name: 'D22 Blue Purple', hex: '#383996', brand: 'MARD' },
  { id: 'D23', name: 'D23 Pale Lilac', hex: '#E9DCF6', brand: 'MARD' },
  { id: 'D24', name: 'D24 Cornflower Blue', hex: '#768AE1', brand: 'MARD' },
  { id: 'D25', name: 'D25 Iris', hex: '#4950C3', brand: 'MARD' },
  { id: 'D26', name: 'D26 Pale Violet', hex: '#D8C7EB', brand: 'MARD' },

  // --- E Series (Pinks) ---
  { id: 'E1', name: 'E1 Shell', hex: '#F4D4CA', brand: 'MARD' },
  { id: 'E2', name: 'E2 Light Pink', hex: '#FEC0DF', brand: 'MARD' },
  { id: 'E3', name: 'E3 Pink', hex: '#F6BDE8', brand: 'MARD' },
  { id: 'E4', name: 'E4 Hot Pink', hex: '#EB619D', brand: 'MARD' },
  { id: 'E5', name: 'E5 Rose', hex: '#F0549E', brand: 'MARD' },
  { id: 'E6', name: 'E6 Dark Rose', hex: '#EC3F74', brand: 'MARD' },
  { id: 'E7', name: 'E7 Berry', hex: '#C73574', brand: 'MARD' },
  { id: 'E8', name: 'E8 Pale Pink', hex: '#FCDCE9', brand: 'MARD' },
  { id: 'E9', name: 'E9 Candy Pink', hex: '#E477CA', brand: 'MARD' },
  { id: 'E10', name: 'E10 Fuchsia', hex: '#D23B96', brand: 'MARD' },
  { id: 'E11', name: 'E11 Blush', hex: '#F7DAD4', brand: 'MARD' },
  { id: 'E12', name: 'E12 Bubblegum', hex: '#F993C1', brand: 'MARD' },
  { id: 'E13', name: 'E13 Raspberry', hex: '#B5016B', brand: 'MARD' },
  { id: 'E14', name: 'E14 Peach Pink', hex: '#F8D4BC', brand: 'MARD' },
  { id: 'E15', name: 'E15 Soft Pink', hex: '#F6C9CC', brand: 'MARD' },
  { id: 'E16', name: 'E16 White Pink', hex: '#FCF5ED', brand: 'MARD' },
  { id: 'E17', name: 'E17 Rose White', hex: '#F7E3EC', brand: 'MARD' },
  { id: 'E18', name: 'E18 Baby Pink', hex: '#FCC9DC', brand: 'MARD' },
  { id: 'E19', name: 'E19 Pastel Pink', hex: '#F5BBD1', brand: 'MARD' },
  { id: 'E20', name: 'E20 Dusty Pink', hex: '#D7C6CE', brand: 'MARD' },
  { id: 'E21', name: 'E21 Mauve', hex: '#C09EA5', brand: 'MARD' },
  { id: 'E22', name: 'E22 Antique Rose', hex: '#B38C9F', brand: 'MARD' },
  { id: 'E23', name: 'E23 Taupe Pink', hex: '#937D8A', brand: 'MARD' },
  { id: 'E24', name: 'E24 Lilac Pink', hex: '#E0BDE5', brand: 'MARD' },

  // --- F Series (Reds/Corals) ---
  { id: 'F1', name: 'F1 Coral Red', hex: '#FD9380', brand: 'MARD' },
  { id: 'F2', name: 'F2 Red', hex: '#F73D4B', brand: 'MARD' },
  { id: 'F3', name: 'F3 Bright Red', hex: '#F04C40', brand: 'MARD' },
  { id: 'F4', name: 'F4 Neon Red', hex: '#F9283F', brand: 'MARD' },
  { id: 'F5', name: 'F5 Crimson', hex: '#E30228', brand: 'MARD' },
  { id: 'F6', name: 'F6 Brick', hex: '#913635', brand: 'MARD' },
  { id: 'F7', name: 'F7 Dark Red', hex: '#911932', brand: 'MARD' },
  { id: 'F8', name: 'F8 Deep Red', hex: '#BB0226', brand: 'MARD' },
  { id: 'F9', name: 'F9 Rose Red', hex: '#E0677A', brand: 'MARD' },
  { id: 'F10', name: 'F10 Brown Red', hex: '#874628', brand: 'MARD' },
  { id: 'F11', name: 'F11 Mahogany', hex: '#5A2223', brand: 'MARD' },
  { id: 'F12', name: 'F12 Watermelon', hex: '#F8516D', brand: 'MARD' },
  { id: 'F13', name: 'F13 Tomato', hex: '#F45C45', brand: 'MARD' },
  { id: 'F14', name: 'F14 Salmon Pink', hex: '#FAADB3', brand: 'MARD' },
  { id: 'F15', name: 'F15 Cherry', hex: '#D50527', brand: 'MARD' },
  { id: 'F16', name: 'F16 Flesh', hex: '#F7BEAA', brand: 'MARD' },
  { id: 'F17', name: 'F17 Terra Cotta', hex: '#EB9C7D', brand: 'MARD' },
  { id: 'F18', name: 'F18 Bronze', hex: '#D07E4A', brand: 'MARD' },
  { id: 'F19', name: 'F19 Rust', hex: '#BF444A', brand: 'MARD' },
  { id: 'F20', name: 'F20 Ash Rose', hex: '#C69495', brand: 'MARD' },
  { id: 'F21', name: 'F21 Pinkish', hex: '#F0B8C6', brand: 'MARD' },
  { id: 'F22', name: 'F22 Pale Rose', hex: '#F7C3D0', brand: 'MARD' },
  { id: 'F23', name: 'F23 Soft Red', hex: '#EE7E6C', brand: 'MARD' },
  { id: 'F24', name: 'F24 Old Rose', hex: '#E09DAF', brand: 'MARD' },
  { id: 'F25', name: 'F25 Cerise', hex: '#E74756', brand: 'MARD' },

  // --- G Series (Browns/Earth Tones) ---
  { id: 'G1', name: 'G1 Pale Flesh', hex: '#FEE4D3', brand: 'MARD' },
  { id: 'G2', name: 'G2 Light Flesh', hex: '#FAC7AA', brand: 'MARD' },
  { id: 'G3', name: 'G3 Flesh', hex: '#F1C4A5', brand: 'MARD' },
  { id: 'G4', name: 'G4 Tan', hex: '#DCB288', brand: 'MARD' },
  { id: 'G5', name: 'G5 Golden Brown', hex: '#E7B252', brand: 'MARD' },
  { id: 'G6', name: 'G6 Ochre', hex: '#E2A113', brand: 'MARD' },
  { id: 'G7', name: 'G7 Brown', hex: '#985C3A', brand: 'MARD' },
  { id: 'G8', name: 'G8 Dark Brown', hex: '#713C2E', brand: 'MARD' },
  { id: 'G9', name: 'G9 Light Brown', hex: '#E4B685', brand: 'MARD' },
  { id: 'G10', name: 'G10 Caramel', hex: '#D98C44', brand: 'MARD' },
  { id: 'G11', name: 'G11 Sand', hex: '#DCC798', brand: 'MARD' },
  { id: 'G12', name: 'G12 Apricot Tan', hex: '#FEC994', brand: 'MARD' },
  { id: 'G13', name: 'G13 Coffee', hex: '#AE724D', brand: 'MARD' },
  { id: 'G14', name: 'G14 Mocha', hex: '#8B694D', brand: 'MARD' },
  { id: 'G15', name: 'G15 Off White', hex: '#F6F9E4', brand: 'MARD' },
  { id: 'G16', name: 'G16 Beige', hex: '#F2D8C1', brand: 'MARD' },
  { id: 'G17', name: 'G17 Cocoa', hex: '#79544E', brand: 'MARD' },
  { id: 'G18', name: 'G18 Pale Peach', hex: '#FFE3D7', brand: 'MARD' },
  { id: 'G19', name: 'G19 Burnt Orange', hex: '#DD7D40', brand: 'MARD' },
  { id: 'G20', name: 'G20 Sienna', hex: '#A5452F', brand: 'MARD' },
  { id: 'G21', name: 'G21 Leather', hex: '#B38660', brand: 'MARD' },

  // --- H Series (Greyscale/Basics) ---
  { id: 'H1', name: 'H1 Transparent', hex: '#E2E8F0', brand: 'MARD' }, // Simulated Transparent
  { id: 'H2', name: 'H2 White', hex: '#FFFFFF', brand: 'MARD' },
  { id: 'H3', name: 'H3 Light Grey', hex: '#B4B4B4', brand: 'MARD' },
  { id: 'H4', name: 'H4 Grey', hex: '#878787', brand: 'MARD' },
  { id: 'H5', name: 'H5 Dark Grey', hex: '#464646', brand: 'MARD' },
  { id: 'H6', name: 'H6 Charcoal', hex: '#2C2C2C', brand: 'MARD' },
  { id: 'H7', name: 'H7 Black', hex: '#010101', brand: 'MARD' },
  { id: 'H8', name: 'H8 Pale Grey', hex: '#E7D6DC', brand: 'MARD' },
  { id: 'H9', name: 'H9 Pearl White', hex: '#EEEEEE', brand: 'MARD' },
  { id: 'H10', name: 'H10 Silver', hex: '#EBEBEB', brand: 'MARD' },
  { id: 'H11', name: 'H11 Aluminium', hex: '#CDCDCD', brand: 'MARD' },
  { id: 'H12', name: 'H12 Cream White', hex: '#FDF6EE', brand: 'MARD' },
  { id: 'H13', name: 'H13 Parchment', hex: '#F5F2D3', brand: 'MARD' },
  { id: 'H14', name: 'H14 Ash', hex: '#CED7D4', brand: 'MARD' },
  { id: 'H15', name: 'H15 Slate Grey', hex: '#98A6A6', brand: 'MARD' },
  { id: 'H16', name: 'H16 Jet Black', hex: '#1B1213', brand: 'MARD' },
  { id: 'H17', name: 'H17 Snow', hex: '#F0EEEF', brand: 'MARD' },
  { id: 'H18', name: 'H18 Ivory', hex: '#FCFEF8', brand: 'MARD' },
  { id: 'H19', name: 'H19 Bone', hex: '#F0EDE6', brand: 'MARD' },
  { id: 'H20', name: 'H20 Steel', hex: '#96A09F', brand: 'MARD' },
  { id: 'H21', name: 'H21 Vanilla', hex: '#F8FCE5', brand: 'MARD' },
  { id: 'H22', name: 'H22 Cool Grey', hex: '#CBCBD3', brand: 'MARD' },
  { id: 'H23', name: 'H23 Warm Grey', hex: '#9B9C96', brand: 'MARD' },

  // --- M Series (Special/Vintage) ---
  { id: 'M1', name: 'M1 Sage Grey', hex: '#BAC7B5', brand: 'MARD' },
  { id: 'M2', name: 'M2 Blue Grey', hex: '#8F9994', brand: 'MARD' },
  { id: 'M3', name: 'M3 Slate', hex: '#6A7D80', brand: 'MARD' },
  { id: 'M4', name: 'M4 Sand', hex: '#E0D4BC', brand: 'MARD' },
  { id: 'M5', name: 'M5 Khaki', hex: '#D1CBAE', brand: 'MARD' },
  { id: 'M6', name: 'M6 Olive Grey', hex: '#B0AA86', brand: 'MARD' },
  { id: 'M7', name: 'M7 Stone', hex: '#B0A796', brand: 'MARD' },
  { id: 'M8', name: 'M8 Mauve Grey', hex: '#AE8082', brand: 'MARD' },
  { id: 'M9', name: 'M9 Earth', hex: '#A68864', brand: 'MARD' },
  { id: 'M10', name: 'M10 Lilac Grey', hex: '#C4B3BB', brand: 'MARD' },
  { id: 'M11', name: 'M11 Purple Grey', hex: '#9D7693', brand: 'MARD' },
  { id: 'M12', name: 'M12 Dark Mauve', hex: '#624B51', brand: 'MARD' },
  { id: 'M13', name: 'M13 Clay', hex: '#C79268', brand: 'MARD' },
  { id: 'M14', name: 'M14 Red Clay', hex: '#C47564', brand: 'MARD' },
  { id: 'M15', name: 'M15 Iron', hex: '#767E7C', brand: 'MARD' },
];

export const GRID_SIZES = [16, 32, 48, 64, 80, 100];
